var width = 10;
var height = 5;
var area = width * height;
console.log('area:', area);
console.log('Type of area:', typeof area);
var bill = 500;
var payment = 600;
var change = payment - bill;
console.log('change:', change);
console.log('Type of change:', typeof change);
var quizzes = 80;
var midterm = 70;
var final = 90;
var grade = (quizzes + midterm + final) / 3;
console.log('grade:', grade);
console.log('Type of grade:', typeof grade);
var firstName = 'Ryan';
var lastName = 'Zhao';
var fullName = firstName + ' ' + lastName;
console.log('fullName:', fullName);
console.log('Type of fullName:', typeof fullName);
var pH = 5;
var isAcidic = pH < 7;
console.log('isAcidic:', isAcidic);
console.log('Type of isAcidic:', typeof isAcidic);
var headCount = 300;
var isSparta = headCount === 300;
console.log('isSparta:', isSparta);
console.log('Type of isSparta:', typeof isSparta);
var motto = fullName;
motto = motto + ' is the GOAT';
console.log('motto:', motto);
console.log('Type of motto:', typeof motto);
