var fullName = 'Ryan Zhao';
var isCool = true;
var totalPets = 0;
var unknown = null;
var never;
console.log('Full name:', fullName);
console.log('fullName type:', typeof fullName);
console.log('Is cool:', isCool);
console.log('isCool type:', typeof isCool);
console.log('Total pets:', totalPets);
console.log('totalPets type:', typeof totalPets);
console.log('unknown:', unknown);
console.log('unkown type:', typeof unknown);
console.log('never:', never);
console.log('never type:', typeof never);
